import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/contexts/ThemeProvider";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";
export const metadata: Metadata = {
  title: "Versus App ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
        <Navbar />
        <main className="bg-background  container mx-auto max-w-275 px-4">
          {children}
        </main>
        <Toaster />
        <Footer />
      </ThemeProvider>
    </div>
  );
}
