import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/contexts/ThemeProvider";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";
export const metadata: Metadata = {
  title: "Versus App ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
        <Navbar />
        <main className="bg-background  container mx-auto max-w-275 px-4">
          {children}
        </main>
        <Toaster
          richColors
          toastOptions={{
            style: {
              color: "var(--primary-foreground)",
              border: "none",
            },
            classNames: {
              toast: "!bg-primary dark:!bg-accent",
              closeButton:
                "!bg-red-300 dark:!bg-red-500 !bg text-foreground transition-colors z-50",
            },
          }}
          duration={2000}
        />
        <Footer />
      </ThemeProvider>
    </div>
  );
}
